//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCursus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursisten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursisten()
        {
            this.Cursisten1 = new HashSet<Cursisten>();
        }
    
        public int CursistNr { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public Nullable<int> MentorNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cursisten> Cursisten1 { get; set; }
        public virtual Cursisten Cursisten2 { get; set; }
    }
}
