//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCursus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFOpleidingenEntities : DbContext
    {
        public EFOpleidingenEntities()
            : base("name=EFOpleidingenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campussen> Campussen { get; set; }
        public virtual DbSet<Docenten> Docenten { get; set; }
        public virtual DbSet<Voorraad> Voorraden { get; set; }
        public virtual DbSet<Boek> Boeken { get; set; }
        public virtual DbSet<Boek2> Boeken2 { get; set; }
        public virtual DbSet<BoekenCursus2> BoekenCursussen2 { get; set; }
        public virtual DbSet<Cursisten> Cursisten { get; set; }
        public virtual DbSet<Cursus> Cursussen { get; set; }
        public virtual DbSet<Cursus2> Cursussen2 { get; set; }
    }
}
