//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taak1_EFBank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFBankEntities : DbContext
    {
        public EFBankEntities()
            : base("name=EFBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klanten> Klanten { get; set; }
        public virtual DbSet<Rekeningen> Rekeningen { get; set; }
        public virtual DbSet<Personeel> Personeel { get; set; }
        public virtual DbSet<TotaleSaldoPerKlant> TotaleSaldoPerKlant { get; set; }
    }
}
